/**
 * The interface's own words: every label, button, heading and screen-reader
 * name that used to be typed straight into a component.
 *
 * Grouped by the part of the site that shows them. `{name}` style holes are
 * filled by `fmt` in `src/i18n/core.js`, so a translation can move them to
 * wherever its grammar puts them; `{ one, other }` pairs are counts, picked by
 * `plural`. Nothing here may carry a claim the content modules would not be
 * allowed to make: `scripts/check-claims.mjs` walks this file too.
 */
import { localize } from '../i18n/core.js'

export const ui = localize('ui', {
  meta: {
    title: 'ORYX GROUP | Our Reliability, Your eXcellence',
    description:
      'ORYX GROUP: building, people, services, solutions. Transport and logistics, workforce, and renovation for organisations across the Netherlands. Our Reliability, Your eXcellence.',
  },

  lang: {
    label: 'Language',
    choose: 'Choose a language',
  },

  app: {
    skip: 'Skip to services',
  },

  nav: {
    primary: 'Primary',
    services: 'Services',
    contact: 'Contact',
    request: 'Request a service',
    requestShort: 'Request',
  },

  common: {
    close: 'Close',
    view: 'View',
    allServices: 'All ORYX services',
    downloadBrochure: 'Download brochure',
    requestService: 'Request a service',
    submitAnytime: 'Requests may be submitted 24/7',
  },

  sound: {
    turnOff: 'Turn background music off',
    turnOn: 'Turn background music on',
    on: 'Sound on',
    off: 'Sound off',
  },

  hero: {
    label: 'Introduction',
    /* Not `enter` or `email` for these labels: those names are data fields
       elsewhere, which the translation step skips by name. */
    go: 'Enter',
    skip: 'Skip intro',
    caption: 'The horns became the mark',
  },

  work: {
    label: 'Services and purpose',
    open: 'Open this service.',
    show: 'Show this service.',
    go: 'Enter',
  },

  footer: {
    start: 'Start a request',
    label: 'Footer',
    services: 'Services',
    group: 'Group',
    purpose: 'Purpose',
    vision: 'Vision',
    mission: 'Mission',
    values: 'Values',
    contact: 'Contact',
    hours: 'Monday to Friday, 08:00 to 18:00',
    privacy: 'Privacy',
    terms: 'Terms',
  },

  transport: {
    unit: 'Dispatch',
    sections: 'Transport sections',
    navNetwork: 'Network',
    navSchedule: 'Schedule',
    navServices: 'Services',
    navCoverage: 'Coverage',
    status: 'Tracked end to end',
    manifest: [
      { dt: 'Origin', dd: 'Amsterdam hub' },
      { dt: 'Service', dd: 'Scheduled and on demand' },
      { dt: 'Reach', dd: 'Five capitals' },
      { dt: 'Proof', dd: 'Signed and timestamped' },
    ],
    processKicker: 'How it runs',
    processHead: 'From brief to proof',
    clients: 'Clients',
    servicesKicker: 'The services',
    servicesHead: 'Five things we run for you',
    whatItIs: 'What it is',
    networkKicker: 'The network',
    networkLine: 'One hub in Amsterdam, and regular runs to four more capitals.',
    mapLabel: 'Route network linking Paris, Luxembourg, Brussels, Amsterdam and Berlin',
    delivered: 'Delivered',
    deliveredMeta: 'Signed 11:20 / Proof returned',
    footServices: 'Services',
    footCoverage: 'Coverage',
    coverage: ['The Netherlands', 'Belgium and Luxembourg', 'France and Germany'],
    footNetwork: 'Network',
    footDispatch: 'Dispatch',
    footBase: 'ORYX Dispatch, a service of ORYX GROUP',
  },

  workforce: {
    unit: 'Workforce',
    sections: 'Workforce sections',
    navCrew: 'Crew',
    navSectors: 'Sectors',
    navWays: 'Ways to hire',
    navMethod: 'Method',
    navTrust: 'Trust',
    methodKicker: 'Method',
    methodHead: 'How we fill a role',
    status: { req: 'On request', qc: 'Qualification required' },
    regKicker: 'What the register covers',
    regHead: 'Twelve sectors',
    regLine: 'Pick your sector to see the roles we supply, or search for a job title.',
    searchLabel: 'Search all {n} roles',
    searchPlaceholder: 'Search a job title, for example forklift, welder, carpenter',
    clear: 'Clear',
    results: 'Search results',
    noMatch: 'Nothing matches “{q}”. Try a shorter word, or open a sector below.',
    showing: 'Showing {shown} of {total}. Type a little more to narrow it down.',
    /* Read out by screen readers as the search updates. */
    matching: '{n} {roles} matching {q}',
    summary: '{sectors} sectors, {roles} roles.',
    roleWord: { one: 'role', other: 'roles' },
    groupWord: { one: 'group', other: 'groups' },
    rolesWeSupply: 'Roles we supply',
    andMore: 'and {n} more',
    brochureNote: 'The brochure lists every role in this sector with a line on what it covers.',
    brochureFlagged: 'Some roles are marked “{req}” or “{qc}” there. Those are confirmed for each assignment.',
    band: 'The twelve sectors in pictures',
    wayGo: 'Request staff this way',
    /* Written into the request's note when a way of hiring is picked. */
    howNote: 'How: {way}',
    situations: [
      'Two people are off sick this week.',
      'A nine-month project needs a fitter.',
      'We want to hire someone, not borrow them.',
      'A whole crew for a new site.',
    ],
    waysKicker: 'Four ways to hire',
    waysHead: 'Which one sounds like your week?',
    waysLine: 'Any role in the register can be supplied in any of these four ways. The job stays the same, and only the way you hire changes.',
    stamp: ['CHECKED FOR', 'THIS ASSIGNMENT'],
    footSectors: 'Sectors',
    footLines: 'Service lines',
    footTalk: 'Talk to us',
    footBase: 'ORYX Workforce, a service of ORYX GROUP',
  },

  crew: {
    kicker: 'How a crew is built',
    line: 'An illustration: one skilled worker first, then the trades around them, and a foreman last.',
    cap: 'In this drawing',
    one: 'One skilled worker',
    small: 'A small team',
    pool: 'A flex pool',
    full: 'A complete project crew',
    level: 'Level {n}',
    list: 'The roles in this example crew',
  },

  renovation: {
    unit: 'ORYX Projects',
    back: 'Return to group',
    sections: 'Renovation sections',
    navDecision: 'Decision',
    navSchedule: 'Schedule',
    navRoute: 'Route',
    navTrust: 'Trust',
    metaSheet: 'Sheet',
    metaServices: 'Services',
    metaWorks: 'Works',
    beforeAfter: 'Before, and after',
    scrubNote: 'Illustration of a typical scope, not a photograph of a completed ORYX project. Project photographs follow once clients give written consent.',
    processKicker: 'How a project runs',
    processHead: 'Seven steps on every project',
    band: 'The nine services in pictures',
    clientsKicker: 'Clients',
    clientsHead: 'Who we work for',
    trustKicker: 'What we promise',
    trustHead: 'Straight answers',
    decision: 'The decision',
    less: 'Less intervention',
    more: 'More intervention',
    chooseLegend: 'Choose a scenario. These are three alternatives for the same property, not three stages of one job. One is chosen, and the other two are not done afterwards.',
    scenario: 'Scenario: {k}',
    marks: 'What the drawing marks',
    qualifiedNote: 'Carried out or supervised by a qualified specialist where required.',
    sectionTitle: 'Section through a four-storey block. Maintain marks the outer envelope; Improve marks the fabric inside it; Transform marks the structure and the plan itself. The building drawn is the same in all three.',
    datum: 'DATUM',
    conds: {
      project: { k: 'Project basis', d: 'Confirmed for each project after property, risk, partner and qualification checks.' },
      qualified: { k: 'Qualified specialist', d: 'Carried out or supervised by a qualified specialist where required.' },
    },
    schedKicker: 'Schedule of works',
    schedHead: 'Nine services',
    schedLede: 'Open a service to see the work it covers.',
    works: { one: '{n} work', other: '{n} works' },
    worksWord: { one: 'work', other: 'works' },
    cardsNote: '{services} services and {works} works in all. ORYX organises delivery of every work. {marked} of them are marked, because they are confirmed for each project or carried out by a qualified specialist.',
    of: 'of {n}',
    covers: 'What it covers',
    afterAlt: 'After renovation',
    before: 'Before',
    after: 'After',
    reveal: 'Reveal the finished space',
    passport: ['PROPERTY', 'PASSPORT'],
    passportTabs: ['Inspections', 'Photos', 'Works', 'Materials', 'Decisions', 'Warranties', 'Maintenance'],
    meterRows: ['Residents', 'Staff', 'Operations'],
    meterNote: 'ILLUSTRATION ONLY. THE VIEW IS BUILT PER PROPERTY.',
    clientMore: 'What we do for them',
    inDutch: 'In Dutch: {name}',
    close: 'Close',
    tb: {
      client: 'Client',
      clientD: 'Housing, public sector, commercial and heritage property',
      discipline: 'Discipline',
      disciplineD: 'Maintenance, renovation and heritage restoration',
      drawn: 'Drawn',
      checked: 'Checked',
      checkedD: 'Contracts',
      date: 'Date',
      sheet: 'Sheet',
      rev: 'Rev',
      project: 'Project',
      projectD: 'ORYX Projects, a service of ORYX GROUP',
      contact: 'Contact',
    },
  },

  request: {
    steps: [
      { k: 'You send the request', d: 'A few details are enough to start.' },
      { k: 'It reaches the right team', d: 'Each service has its own inbox, so nothing is passed around.' },
      { k: 'They contact you', d: 'To agree the details and the next step with you.' },
    ],
    errors: {
      name: 'Please add your name.',
      emailMissing: 'Please add your email address.',
      emailBad: 'That email address does not look complete.',
      phone: 'That phone number looks too short.',
      service: 'Please choose a service.',
      sub: 'Please choose one option.',
    },
    optional: 'Optional',
    close: 'Close',
    kicker: 'Request a service',
    title: 'Tell us what you need',
    lede: 'Choose the service, add a few details and send. Your request goes straight to the team that handles it.',
    mailtoTitle: 'One more step',
    /* The address sits between these two halves, as a link. */
    mailtoBefore: 'Your mail app should have opened with the request already written and addressed to',
    mailtoAfter: 'Press send there to finish. If nothing opened, use that link to try again, or go back and copy what you wrote.',
    sentTitle: 'Request sent',
    sentBody: 'Thank you, {name}. Your request is with the {team} team, and they will contact you at {email} to agree the details.',
    back: 'Back to the site',
    backToRequest: 'Back to my request',
    another: 'Send another request',
    name: 'Full name',
    emailLabel: 'Email',
    company: 'Company',
    phone: 'Phone',
    service: 'Service',
    chooseService: 'Choose a service',
    chooseOne: 'Choose one',
    note: 'Note',
    notePlaceholder: 'Anything that helps us understand the job: dates, location, numbers.',
    failed: 'The request could not be sent just now. Please try again.',
    failedWrite: 'The request could not be sent just now. Please try again, or write to {email}.',
    sending: 'Sending',
    send: 'Send request',
    privacy: 'Your details are used only to answer this request.',
  },

  /* The PDF brochures, which `scripts/build-brochures.mjs` writes once per
     language. Everything else in them is the content modules' own copy. */
  brochure: {
    sector: 'Sector {n} of {total}',
    service: 'Service {n} of {total}',
    statRoles: 'Roles',
    statGroups: 'Groups',
    statWays: 'Ways to hire',
    statWorks: 'Works',
    statService: 'Service',
    waysHead: 'Four ways to work with us',
    flagged: '{req} means the role is supplied subject to confirmation. {qc} means the role calls for a certificate, and a certificate does not automatically grant authority.',
    contact: 'Tell us what you need and the {team} team will contact you to agree the details.',
    writeTo: 'Write to',
  },
})
